# Generated by Django 5.2.10 on 2026-04-03 09:27

import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='métadonnées')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='auteur')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'appartement")),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL simplifiée')),
                ('location', models.CharField(choices=[('douala', 'Douala'), ('yaounde', 'Yaoundé'), ('kribi', 'Kribi')], max_length=50, verbose_name='Localisation')),
                ('neighborhood', models.CharField(help_text='Ex: Bastos, Bonapriso', max_length=100, verbose_name='Quartier')),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix par nuit (FCFA)')),
                ('bedrooms', models.PositiveIntegerField(default=1, verbose_name='Chambres')),
                ('bathrooms', models.PositiveIntegerField(default=1, verbose_name='Salles de bain')),
                ('max_guests', models.PositiveIntegerField(default=2, verbose_name='Voyageurs max')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='appartements/', verbose_name='Image principale')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mettre en avant')),
                ('amenities', models.JSONField(blank=True, default=list, verbose_name='Équipements')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Appartement',
                'verbose_name_plural': 'Appartements',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='métadonnées')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='auteur')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('subject', models.CharField(max_length=255, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='métadonnées')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='auteur')),
                ('site_name', models.CharField(default='MatRox Residence', max_length=100, verbose_name='Nom du site')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone de contact')),
                ('office_address', models.TextField(blank=True, verbose_name='Adresse du bureau')),
                ('logo_text_main', models.CharField(default='MatRox', max_length=50, verbose_name='Texte Logo (Principal)')),
                ('logo_text_sub', models.CharField(default='Residence', max_length=50, verbose_name='Texte Logo (Sous-titre)')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('whatsapp_number', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp')),
            ],
            options={
                'verbose_name': 'Paramètres',
                'verbose_name_plural': 'Paramètres',
            },
        ),
    ]
