# Generated by Django 5.2.10 on 2026-04-03 09:32

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppartementImage',
            fields=[
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='métadonnées')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='auteur')),
                ('image', models.ImageField(upload_to='appartements/gallery/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Texte alternatif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.appartement')),
            ],
            options={
                'verbose_name': "Image d'appartement",
                'verbose_name_plural': "Images d'appartement",
                'ordering': ('order', 'created'),
            },
        ),
    ]
