# Generated by Django 5.2.10 on 2026-04-06 04:52

import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appartementimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='supprimé')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='métadonnées')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='auteur')),
                ('client_name', models.CharField(max_length=100, verbose_name='Nom du client')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='Profession/Titre')),
                ('content', models.TextField(verbose_name='Contenu du témoignage')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='Note (sur 5)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Affiché publiquement')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ('-created',),
            },
        ),
    ]
