# Generated by Django 5.2.10 on 2026-04-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testimonial_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartement',
            name='location',
            field=models.CharField(choices=[('douala', 'Douala'), ('yaounde', 'Yaoundé'), ('kribi', 'Kribi'), ('bafoussam', 'Bafoussam')], max_length=50, verbose_name='Localisation'),
        ),
    ]
